server {
    listen 80;
    client_max_body_size 512M;

    # Frontend
    location / {
        proxy_pass http://frontend:80;
        proxy_set_header Host $host;
    }

    # Manager API
    location /manager/ {
        proxy_pass http://manager:9000/;
        proxy_set_header Host $host;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    # PostgREST
    location /postgrest/ {
        proxy_pass http://postgrest:3000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Swagger UI
    location /swagger/ {
        proxy_pass http://swagger:8080/;
        proxy_set_header Host $host;
    }
}
